#Local-only config
spring:
  application:
    name: author-service-client
  data:
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.database: test

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
    register-with-eureka: true 
    
ribbon:
  eureka:
    enabled: true    

logging:
  level:
    #ROOT: DEBUG
    org.springframework.web: ERROR
    src.main.java: DEBUG
    pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: c:/logs/author.log    
   



 